spring.application.name=exchangecurrencyapp-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/exchangecurrency
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

logging.level.com.exchangecurrencyapp=INFO
